### ISSUE TITLE
Error when trying to edit a Blog

### ISSUE THREAD

**Issue by tmbb** [talonframework/talon_blog_demo#1]
Going to the edit URL url: `http://localhost:4000/talon/blogs/5f8d5f05-52dc-4b78-9487-957c990ac32b/edit` raises this error:

![image](https://user-images.githubusercontent.com/2668874/26978514-adf66448-4d23-11e7-9128-d9ca868866fd.png)

**Comment by dsnider** [comment]
@tmbb It work for me, but the asset handling in the README is not correct for Phoenix 1.3. I'll fix that, but can you try running `cd assets && npm install && cd ..` and let me know if that helps things?

**Comment by smpallen99** [comment]
I've fixed this issue in the local branch I'm working on. It has to do with an issue inflecting the display name field of an association.

**Comment by smpallen99** [comment]
Working now
